app:
  node_id: coordinator
  coordinator: true
  storage: true

auth:
  jwt_secret: "change-me"
  access_token_duration: "30m"
  refresh_token_duration: "8h"

http:
  address: ":8080"

database:
  driver: "sqlite"
  dsn: "dropoutbox.db"
  auto_migrate: true
#  driver: "postgres"
#  dsn: "host=localhost user=postgres password=postgres dbname=dropoutbox port=5432 sslmode=disable"
#  auto_migrate: true

seed:
  admin_name: admin
  admin_password: change-me
